/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TitelblattRouteImport } from './routes/titelblatt'
import { Route as LebenslaufRouteImport } from './routes/lebenslauf'
import { Route as AnschreibenRouteImport } from './routes/anschreiben'
import { Route as IndexRouteImport } from './routes/index'

const TitelblattRoute = TitelblattRouteImport.update({
  id: '/titelblatt',
  path: '/titelblatt',
  getParentRoute: () => rootRouteImport,
} as any)
const LebenslaufRoute = LebenslaufRouteImport.update({
  id: '/lebenslauf',
  path: '/lebenslauf',
  getParentRoute: () => rootRouteImport,
} as any)
const AnschreibenRoute = AnschreibenRouteImport.update({
  id: '/anschreiben',
  path: '/anschreiben',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anschreiben': typeof AnschreibenRoute
  '/lebenslauf': typeof LebenslaufRoute
  '/titelblatt': typeof TitelblattRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anschreiben': typeof AnschreibenRoute
  '/lebenslauf': typeof LebenslaufRoute
  '/titelblatt': typeof TitelblattRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anschreiben': typeof AnschreibenRoute
  '/lebenslauf': typeof LebenslaufRoute
  '/titelblatt': typeof TitelblattRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anschreiben' | '/lebenslauf' | '/titelblatt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anschreiben' | '/lebenslauf' | '/titelblatt'
  id: '__root__' | '/' | '/anschreiben' | '/lebenslauf' | '/titelblatt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnschreibenRoute: typeof AnschreibenRoute
  LebenslaufRoute: typeof LebenslaufRoute
  TitelblattRoute: typeof TitelblattRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/titelblatt': {
      id: '/titelblatt'
      path: '/titelblatt'
      fullPath: '/titelblatt'
      preLoaderRoute: typeof TitelblattRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lebenslauf': {
      id: '/lebenslauf'
      path: '/lebenslauf'
      fullPath: '/lebenslauf'
      preLoaderRoute: typeof LebenslaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anschreiben': {
      id: '/anschreiben'
      path: '/anschreiben'
      fullPath: '/anschreiben'
      preLoaderRoute: typeof AnschreibenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnschreibenRoute: AnschreibenRoute,
  LebenslaufRoute: LebenslaufRoute,
  TitelblattRoute: TitelblattRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
