import type { Alignment, PageMargins } from "./model";

/** Page-width-relative nonsemantic geometry; absent height follows its chrome band. */
export type TemplateMotif = {
  shape: "rect" | "circle" | "path";
  path?: string;
  xFraction: number;
  widthFraction: number;
  topMm: number;
  heightMm?: number;
  cornerRadiiMm?: readonly [number, number, number, number];
  /** Omit fill for border-only motifs such as rings. */
  fillSlot?: string;
  /** Fixed nonsemantic paint (e.g. a white bloom), independent of editable palette slots. */
  fillColor?: string;
  stroke?: { slot: string; widthMm: number };
  endSlot?: string;
  gradientStops?: readonly { slot: string; offsetPct: number }[];
  angleDeg?: number;
  radialFade?: { innerPct: number; outerPct: number };
  opacity?: number;
  repeat?: "first" | "continuation";
};

/** Configuration only: templates never receive XML or a package. */
export type TemplateDefinition = {
  id: string;
  archetype: "minimal" | "organic" | "editorial" | "sidebar" | "graphic" | "dark";
  typography: { font: string; bodyPt: number; namePt: number; headingPt: number; heroPt: number };
  colors: { ink: string; accent: string; paper: string };
  margins: PageMargins;
  /** Pure app palette rules resolve readable interior ink/paper independently of cover ink. */
  interiorPaletteSource?: "dossier";
  cover: {
    /** Native cover composition can use its own page gutters. Interior margins remain independent. */
    margins?: PageMargins;
    /** Built-in semantic roles may inherit the dossier font; explicit/custom fonts keep precedence. */
    fontSource?: "dossier";
    order: readonly string[];
    align: Alignment;
    heroSpaceMm: number;
    photoWidthMm: number;
    photoAlign?: Alignment;
    /** Native paragraph defaults; explicit saved field alignment keeps precedence. */
    fieldAlignments?: Readonly<Record<string, Alignment>>;
    /** Palette roles for native field defaults; explicit saved colors retain precedence. */
    fieldColorSlots?: Readonly<Record<string, string>>;
    /** Apply field defaults to palette-bound inline runs; literal authored colors stay explicit. */
    fieldPaletteMode?: "uniform";
    /** Semantic field leads in native flow, including fields grouped in cover cells. */
    fieldSpaceBeforeMm?: Readonly<Record<string, number>>;
    rows?: readonly {
      fields: readonly (string | readonly string[])[];
      widths: readonly number[];
      fillSlot?: string;
      beforeMm?: number;
    }[];
    heroLeadMm?: number;
    photoAbsentLeadMm?: number;
    decorationPlacement?: "first-header";
    motifs?: readonly TemplateMotif[];
  };
  letter: {
    paragraphSpaceMm: number;
    lineHeight: number;
    recipientGapMm: number;
    fontSource?: "standalone" | "dossier";
    compactMasthead?: { heightMm: number; widthMm: number; fillSlot: string };
    keepTailTogether?: boolean;
  };
  chrome: {
    headerDistanceMm: number;
    footerDistanceMm: number;
    defaultContact?: { heightMm: number; gapMm: number };
    ignoreEmptyHeader?: boolean;
    lineMetricFactor?: number;
    band?: {
      /** Own semantic descriptor paint instead of the historical browser chrome defaults. */
      surfaceSource?: "descriptor";
      /** Motif-only chrome leaves editable contact text on the paper surface. */
      surface?: "band" | "motifs";
      fillSlot: string;
      accentSlot: string;
      compactFirstMm: number;
      compactContinuationMm: number;
      motifs?: readonly TemplateMotif[];
      /** Quiet page paint when the running header is disabled. */
      noneMotifs?: readonly TemplateMotif[];
      circles?: readonly {
        rightMm: number;
        topMm: number;
        diameterMm: number;
        opacity: number;
        strokeMm?: number;
      }[];
    };
  };
  cv: { sectionSpaceMm: number; headingRule: boolean; sidebarFraction: number };
  /** Quiet page paint independent of running contact chrome; repeats in native header stories. */
  pageMotifs?: Partial<Record<"letter" | "cv", readonly TemplateMotif[]>>;
  artwork: readonly { asset: string; semanticText: false }[];
};
export const BRIEF: TemplateDefinition = {
  id: "brief",
  archetype: "minimal",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 32 },
  colors: { ink: "111111", accent: "244A61", paper: "FFFFFF" },
  margins: { top: 20, right: 20, bottom: 18, left: 20 },
  cover: {
    order: [
      "eyebrow",
      "datum",
      "foto",
      "kicker",
      "beruf",
      "name",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "empfaengerTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 12,
    photoWidthMm: 40,
  },
  letter: { paragraphSpaceMm: 3, lineHeight: 1.2, recipientGapMm: 12, fontSource: "standalone" },
  chrome: { headerDistanceMm: 16, footerDistanceMm: 12 },
  cv: { sectionSpaceMm: 4, headingRule: true, sidebarFraction: 0.3 },
  artwork: [],
};
/** Isolated stress candidate; registration does not imply Word acceptance. */
export const WARM: TemplateDefinition = {
  id: "freundlich",
  archetype: "organic",
  typography: { font: "Georgia", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 24 },
  colors: { ink: "0B1F24", accent: "0F766E", paper: "FFF9EF" },
  margins: { top: 20, right: 22, bottom: 22, left: 24 },
  cover: {
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
    ],
    align: "center",
    heroSpaceMm: 0,
    photoWidthMm: 60,
    photoAlign: "center",
    heroLeadMm: 55,
    photoAbsentLeadMm: 115,
    decorationPlacement: "first-header",
    rows: [
      { fields: ["eyebrow", "ortDatum"], widths: [1, 1], fillSlot: "primary" },
      { fields: ["kontaktTitel", "anTitel"], widths: [1, 1] },
      { fields: ["kontakt", "empfaenger"], widths: [1, 1] },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    compactMasthead: { heightMm: 52, widthMm: 82, fillSlot: "primary" },
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 44, gapMm: 4 },
    band: {
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 52,
      compactContinuationMm: 14,
      circles: [
        { rightMm: -24, topMm: -41, diameterMm: 92, opacity: 0.78, strokeMm: 0.8 },
        { rightMm: -13, topMm: -31, diameterMm: 72, opacity: 0.72 },
      ],
    },
  },
  cv: { sectionSpaceMm: 4, headingRule: true, sidebarFraction: 0.3 },
  artwork: [],
};
/** Geometric stress candidate: native cover columns and declarative diagonal paint. */
export const PRISM: TemplateDefinition = {
  id: "prism",
  archetype: "graphic",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 24 },
  colors: { ink: "18223A", accent: "6F95F2", paper: "F5F7FC" },
  margins: { top: 20, right: 20, bottom: 18, left: 20 },
  cover: {
    order: [
      "eyebrow",
      "ortDatum",
      "name",
      "beruf",
      "lehrbeginn",
      "foto",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 60,
    photoAlign: "right",
    decorationPlacement: "first-header",
    rows: [
      { fields: ["eyebrow", "ortDatum"], widths: [1, 1], fillSlot: "primary" },
      { fields: [["name", "beruf", "lehrbeginn"], "foto"], widths: [0.62, 0.38], beforeMm: 90 },
      {
        fields: [
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger", "beilagenTitel", "beilagen"],
        ],
        widths: [1, 1],
        beforeMm: 12,
      },
    ],
    motifs: [
      {
        shape: "path",
        path: "M 0 0 L 100 0 L 100 72 L 0 100",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 111,
        fillSlot: "primary",
      },
      {
        shape: "path",
        path: "M 28 0 L 100 0 L 100 100 L 0 78",
        xFraction: 0.51,
        widthFraction: 0.49,
        topMm: 0,
        heightMm: 111,
        fillSlot: "secondary",
        opacity: 0.94,
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 44, gapMm: 4 },
    band: {
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
      surfaceSource: "descriptor",
      motifs: [
        {
          shape: "path",
          path: "M 28 0 L 100 0 L 100 100 L 0 78",
          xFraction: 0.61,
          widthFraction: 0.39,
          topMm: 0,
          fillSlot: "secondary",
        },
      ],
    },
  },
  cv: { sectionSpaceMm: 4, headingRule: true, sidebarFraction: 0.3 },
  artwork: [],
};
/** Organic stress candidate: photo-left cover hero and quiet page paint, native text throughout. */
export const HUMAN: TemplateDefinition = {
  id: "human",
  archetype: "organic",
  typography: { font: "Trebuchet MS", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "3B2A22", accent: "9C5B3C", paper: "FDF6F0" },
  margins: { top: 24, right: 23, bottom: 22, left: 25 },
  cover: {
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "kicker",
      "beruf",
      "name",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 46,
    photoAlign: "left",
    decorationPlacement: "first-header",
    rows: [
      { fields: ["eyebrow", "ortDatum"], widths: [0.62, 0.38] },
      { fields: ["foto", ["kicker", "beruf"]], widths: [0.35, 0.65], beforeMm: 14 },
      { fields: [["name", "lehrbeginn"]], widths: [1], beforeMm: 18 },
      {
        fields: [
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger"],
        ],
        widths: [1, 1],
        beforeMm: 28,
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: true, sidebarFraction: 0.3 },
  pageMotifs: {
    letter: [
      {
        shape: "circle",
        xFraction: 150 / 210,
        widthFraction: 82 / 210,
        topMm: -16,
        heightMm: 62,
        fillSlot: "secondary",
        opacity: 0.3,
      },
      {
        shape: "circle",
        xFraction: -18 / 210,
        widthFraction: 58 / 210,
        topMm: 242,
        heightMm: 40,
        fillSlot: "primary",
        opacity: 0.14,
      },
    ],
    cv: [
      {
        shape: "circle",
        xFraction: 150 / 210,
        widthFraction: 82 / 210,
        topMm: -16,
        heightMm: 62,
        fillSlot: "secondary",
        opacity: 0.3,
      },
    ],
  },
  artwork: [],
};
/** Offset circular cover field and restrained interior stationery, all semantic content native. */
export const ORBIT: TemplateDefinition = {
  id: "orbit",
  archetype: "graphic",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "19182D", accent: "625FE8", paper: "F7F8FC" },
  margins: { top: 24, right: 25, bottom: 22, left: 26 },
  cover: {
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 60,
    photoAlign: "right",
    heroLeadMm: 36,
    photoAbsentLeadMm: 102,
    fieldAlignments: {
      eyebrow: "right",
      ortDatum: "right",
      name: "left",
      beruf: "left",
      lehrbeginn: "left",
    },
    decorationPlacement: "first-header",
    rows: [
      { fields: [[], ["eyebrow", "ortDatum"]], widths: [0.5, 0.5] },
      {
        fields: [
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger", "beilagenTitel", "beilagen"],
        ],
        widths: [1, 1],
        beforeMm: 24,
      },
    ],
    motifs: [
      {
        shape: "circle",
        xFraction: 106 / 210,
        widthFraction: 138 / 210,
        topMm: -34,
        heightMm: 138,
        fillSlot: "primary",
      },
      {
        shape: "circle",
        xFraction: 72 / 210,
        widthFraction: 82 / 210,
        topMm: 58,
        heightMm: 82,
        fillSlot: "secondary",
        opacity: 0.9,
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: true, sidebarFraction: 0.3 },
  pageMotifs: {
    letter: [
      { shape: "rect", xFraction: 0, widthFraction: 1, topMm: 0, heightMm: 7, fillSlot: "primary" },
      {
        shape: "circle",
        xFraction: 184 / 210,
        widthFraction: 18 / 210,
        topMm: -4,
        heightMm: 18,
        fillSlot: "secondary",
        opacity: 0.34,
      },
    ],
    cv: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 10,
        fillSlot: "primary",
      },
      {
        shape: "circle",
        xFraction: 180 / 210,
        widthFraction: 22 / 210,
        topMm: -6,
        heightMm: 22,
        stroke: { slot: "secondary", widthMm: 2 },
        opacity: 0.52,
      },
    ],
  },
  artwork: [],
};
/** Asymmetric rounded masthead and coral bay; semantic content stays in native flow. */
export const COVE: TemplateDefinition = {
  id: "cove",
  archetype: "graphic",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "2B1F2A", accent: "B84959", paper: "FFF8F5" },
  margins: { top: 26, right: 24, bottom: 24, left: 26 },
  cover: {
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 60,
    photoAlign: "right",
    heroLeadMm: 32,
    photoAbsentLeadMm: 58,
    fieldAlignments: {
      eyebrow: "left",
      ortDatum: "left",
      name: "left",
      beruf: "left",
      lehrbeginn: "left",
    },
    decorationPlacement: "first-header",
    rows: [
      { fields: [["eyebrow", "ortDatum"], []], widths: [0.65, 0.35] },
      {
        fields: [
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger", "beilagenTitel", "beilagen"],
        ],
        widths: [1, 1],
        beforeMm: 10,
      },
    ],
    motifs: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 76,
        fillSlot: "primary",
        cornerRadiiMm: [0, 0, 46, 0],
      },
      {
        shape: "rect",
        xFraction: 134 / 210,
        widthFraction: 76 / 210,
        topMm: 0,
        heightMm: 108,
        fillSlot: "secondary",
        opacity: 0.94,
        cornerRadiiMm: [0, 0, 0, 48],
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
      motifs: [
        {
          shape: "rect",
          xFraction: 156 / 210,
          widthFraction: 54 / 210,
          topMm: 0,
          fillSlot: "secondary",
          opacity: 0.94,
          cornerRadiiMm: [0, 0, 0, 17],
        },
      ],
      noneMotifs: [
        {
          shape: "rect",
          xFraction: 0,
          widthFraction: 1,
          topMm: 0,
          heightMm: 8,
          fillSlot: "primary",
        },
        {
          shape: "rect",
          xFraction: 164 / 210,
          widthFraction: 46 / 210,
          topMm: 0,
          heightMm: 18,
          fillSlot: "secondary",
          opacity: 0.92,
          cornerRadiiMm: [0, 0, 0, 9],
        },
      ],
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: true, sidebarFraction: 0.3 },
  artwork: [],
};
/** Rounded luminous stationery: all paint is generic and all fields are native. */
export const GLOW: TemplateDefinition = {
  id: "glow",
  archetype: "organic",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "172033", accent: "4F46E5", paper: "F7F9FF" },
  margins: { top: 27, right: 24, bottom: 23, left: 25 },
  cover: {
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 60,
    photoAlign: "right",
    heroLeadMm: 10,
    photoAbsentLeadMm: 36,
    fieldAlignments: {
      eyebrow: "left",
      ortDatum: "right",
      name: "left",
      beruf: "left",
      lehrbeginn: "left",
    },
    decorationPlacement: "first-header",
    rows: [
      { fields: ["eyebrow", "ortDatum"], widths: [0.5, 0.5] },
      {
        fields: [
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger", "beilagenTitel", "beilagen"],
        ],
        widths: [1, 1],
        beforeMm: 14,
      },
    ],
    motifs: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 30,
        fillSlot: "primary",
        endSlot: "secondary",
        angleDeg: 100,
        cornerRadiiMm: [0, 0, 16, 0],
      },
      {
        shape: "rect",
        xFraction: 150 / 210,
        widthFraction: 48 / 210,
        topMm: 4,
        heightMm: 18,
        fillSlot: "secondary",
        opacity: 0.28,
        cornerRadiiMm: [9, 9, 9, 9],
      },
      {
        shape: "rect",
        xFraction: 20 / 210,
        widthFraction: 46 / 210,
        topMm: 31.5,
        heightMm: 1.4,
        fillSlot: "accent",
        opacity: 0.96,
        cornerRadiiMm: [0.7, 0.7, 0.7, 0.7],
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
      motifs: [
        {
          shape: "rect",
          xFraction: 0,
          widthFraction: 1,
          topMm: 0,
          fillSlot: "primary",
          endSlot: "secondary",
          angleDeg: 104,
          opacity: 0.24,
        },
        {
          shape: "circle",
          xFraction: 174 / 210,
          widthFraction: 42 / 210,
          topMm: 0,
          heightMm: 42,
          fillSlot: "secondary",
          opacity: 0.52,
          radialFade: { innerPct: 0, outerPct: 90 },
        },
        {
          shape: "rect",
          xFraction: 161 / 210,
          widthFraction: 34 / 210,
          topMm: 10.5,
          heightMm: 0.7,
          fillSlot: "bg",
          endSlot: "secondary",
          angleDeg: 90,
          opacity: 0.7,
          cornerRadiiMm: [0.35, 0.35, 0.35, 0.35],
        },
      ],
      noneMotifs: [
        {
          shape: "circle",
          xFraction: 170 / 210,
          widthFraction: 54 / 210,
          topMm: -10,
          heightMm: 54,
          fillSlot: "primary",
          opacity: 0.12,
          radialFade: { innerPct: 0, outerPct: 100 },
        },
      ],
    },
  },
  cv: { sectionSpaceMm: 2.8, headingRule: true, sidebarFraction: 0.3 },
  artwork: [],
};
/** Horizontal navy-to-blue stationery reuses the same corner/gradient/photo primitives. */
export const HORIZON: TemplateDefinition = {
  id: "horizon",
  archetype: "editorial",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "152033", accent: "6FC3FF", paper: "F6F9FF" },
  margins: { top: 32, right: 23, bottom: 23, left: 25 },
  cover: {
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 60,
    photoAlign: "right",
    heroLeadMm: 24,
    photoAbsentLeadMm: 86,
    fieldAlignments: {
      eyebrow: "left",
      ortDatum: "right",
      name: "center",
      beruf: "center",
      lehrbeginn: "center",
    },
    decorationPlacement: "first-header",
    rows: [
      { fields: ["eyebrow", "ortDatum"], widths: [0.5, 0.5] },
      {
        fields: [
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger", "beilagenTitel", "beilagen"],
        ],
        widths: [1, 1],
        beforeMm: 12,
      },
    ],
    motifs: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 108,
        fillSlot: "primary",
        endSlot: "secondary",
        angleDeg: 90,
        cornerRadiiMm: [0, 0, 72, 0],
      },
      {
        shape: "circle",
        xFraction: 100 / 210,
        widthFraction: 132 / 210,
        topMm: -24,
        heightMm: 132,
        fillSlot: "secondary",
        opacity: 0.52,
        radialFade: { innerPct: 0, outerPct: 100 },
      },
      {
        shape: "circle",
        xFraction: 74 / 210,
        widthFraction: 86 / 210,
        topMm: 74,
        heightMm: 86,
        fillSlot: "secondary",
        opacity: 0.18,
        radialFade: { innerPct: 0, outerPct: 100 },
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
      motifs: [
        {
          shape: "rect",
          xFraction: 0,
          widthFraction: 1,
          topMm: 0,
          fillSlot: "primary",
          endSlot: "secondary",
          angleDeg: 90,
        },
      ],
      noneMotifs: [
        {
          shape: "rect",
          xFraction: 0,
          widthFraction: 1,
          topMm: 0,
          heightMm: 10,
          fillSlot: "primary",
          endSlot: "secondary",
          angleDeg: 90,
        },
      ],
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: true, sidebarFraction: 0.3 },
  artwork: [],
};
/** Editorial stationery with native contact text on paper, a cap and one brass rule. */
export const MONO_LUXE: TemplateDefinition = {
  id: "monoLuxe",
  archetype: "editorial",
  typography: { font: "Georgia", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "171717", accent: "8E6F42", paper: "F8F6F1" },
  margins: { top: 27, right: 27, bottom: 24, left: 27 },
  cover: {
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 60,
    photoAlign: "right",
    heroLeadMm: 14,
    photoAbsentLeadMm: 50,
    fieldAlignments: {
      eyebrow: "left",
      ortDatum: "right",
      name: "left",
      beruf: "left",
      lehrbeginn: "left",
    },
    decorationPlacement: "first-header",
    rows: [
      { fields: ["eyebrow", "ortDatum"], widths: [1, 1] },
      {
        fields: [
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger", "beilagenTitel", "beilagen"],
        ],
        widths: [1, 1],
        beforeMm: 14,
      },
    ],
    motifs: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 36,
        fillSlot: "primary",
      },
      {
        shape: "rect",
        xFraction: 28 / 210,
        widthFraction: 154 / 210,
        topMm: 35.2,
        heightMm: 0.55,
        fillSlot: "secondary",
        opacity: 0.82,
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      surface: "motifs",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
      motifs: [
        {
          shape: "rect",
          xFraction: 0,
          widthFraction: 1,
          topMm: 0,
          heightMm: 3,
          fillSlot: "primary",
        },
        {
          shape: "rect",
          xFraction: 27 / 210,
          widthFraction: 156 / 210,
          topMm: 3,
          heightMm: 0.45,
          fillSlot: "secondary",
          opacity: 0.78,
        },
      ],
      noneMotifs: [
        {
          shape: "rect",
          xFraction: 0,
          widthFraction: 1,
          topMm: 0,
          heightMm: 3,
          fillSlot: "primary",
        },
        {
          shape: "rect",
          xFraction: 27 / 210,
          widthFraction: 156 / 210,
          topMm: 3,
          heightMm: 0.45,
          fillSlot: "secondary",
          opacity: 0.78,
        },
      ],
    },
  },
  cv: { sectionSpaceMm: 3.2, headingRule: true, sidebarFraction: 0.3 },
  artwork: [],
};
/** Editorial index stationery: cover columns and quiet nonsemantic page rails. */
export const LEDGER: TemplateDefinition = {
  id: "ledger",
  archetype: "editorial",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "20262C", accent: "B56A43", paper: "F7F4EE" },
  margins: { top: 26, right: 24, bottom: 24, left: 33 },
  cover: {
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 60,
    photoAlign: "left",
    fieldAlignments: {
      eyebrow: "left",
      ortDatum: "right",
      name: "left",
      beruf: "left",
      lehrbeginn: "left",
      kontaktTitel: "left",
      kontakt: "left",
    },
    decorationPlacement: "first-header",
    rows: [
      { fields: ["eyebrow", "ortDatum"], widths: [1, 1] },
      {
        fields: ["foto", [], ["name", "beruf", "lehrbeginn"]],
        widths: [0.34, 0.05, 0.61],
        beforeMm: 20,
      },
      {
        fields: [
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger", "beilagenTitel", "beilagen"],
        ],
        widths: [0.36, 0.64],
        beforeMm: 20,
      },
    ],
    motifs: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 36,
        fillSlot: "primary",
      },
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 64 / 210,
        topMm: 36,
        heightMm: 261,
        fillSlot: "secondary",
        opacity: 0.72,
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: true, sidebarFraction: 0.3 },
  pageMotifs: {
    letter: [
      {
        shape: "rect",
        xFraction: 12 / 210,
        widthFraction: 9 / 210,
        topMm: 0,
        heightMm: 297,
        fillSlot: "secondary",
        opacity: 0.42,
      },
      {
        shape: "rect",
        xFraction: 22 / 210,
        widthFraction: 0.45 / 210,
        topMm: 0,
        heightMm: 297,
        fillSlot: "primary",
        opacity: 0.6,
      },
      {
        shape: "rect",
        xFraction: 33 / 210,
        widthFraction: 153 / 210,
        topMm: 3,
        heightMm: 0.45,
        fillSlot: "accent",
        opacity: 0.78,
      },
    ],
    cv: [
      {
        shape: "rect",
        xFraction: 12 / 210,
        widthFraction: 9 / 210,
        topMm: 0,
        heightMm: 297,
        fillSlot: "secondary",
        opacity: 0.42,
      },
      {
        shape: "rect",
        xFraction: 22 / 210,
        widthFraction: 0.45 / 210,
        topMm: 0,
        heightMm: 297,
        fillSlot: "primary",
        opacity: 0.6,
      },
      {
        shape: "rect",
        xFraction: 33 / 210,
        widthFraction: 153 / 210,
        topMm: 3,
        heightMm: 0.45,
        fillSlot: "accent",
        opacity: 0.78,
      },
    ],
  },
  artwork: [],
};
/** Forest rail and growing native gold hero; quiet interior chrome reuses shared motifs. */
export const RIBBON: TemplateDefinition = {
  id: "ribbon",
  archetype: "editorial",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "1A302A", accent: "A57A2D", paper: "FAFBF7" },
  margins: { top: 33, right: 24, bottom: 25, left: 26 },
  cover: {
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 60,
    photoAlign: "left",
    fieldAlignments: {
      eyebrow: "left",
      ortDatum: "right",
      name: "left",
      beruf: "left",
      lehrbeginn: "left",
      kontaktTitel: "left",
      kontakt: "left",
    },
    fieldColorSlots: { kontaktTitel: "ink", kontakt: "ink" },
    decorationPlacement: "first-header",
    rows: [
      { fields: ["eyebrow", "ortDatum"], widths: [0.28, 0.72], fillSlot: "primary" },
      {
        fields: ["foto", [], ["name", "beruf", "lehrbeginn"]],
        widths: [0.34, 0.05, 0.61],
        fillSlot: "secondary",
        beforeMm: 16,
      },
      {
        fields: [
          [],
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger", "beilagenTitel", "beilagen"],
        ],
        widths: [0.2, 0.4, 0.4],
        beforeMm: 20,
      },
    ],
    motifs: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 56 / 210,
        topMm: 0,
        heightMm: 297,
        fillSlot: "primary",
        cornerRadiiMm: [0, 0, 28, 0],
      },
      {
        shape: "rect",
        xFraction: 44 / 210,
        widthFraction: 166 / 210,
        topMm: 28,
        heightMm: 58,
        fillSlot: "secondary",
        opacity: 0.96,
        cornerRadiiMm: [0, 29, 29, 0],
      },
      {
        shape: "circle",
        xFraction: -18 / 210,
        widthFraction: 92 / 210,
        topMm: 205,
        heightMm: 92,
        fillSlot: "secondary",
        opacity: 0.2,
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
      motifs: [
        {
          shape: "rect",
          xFraction: 180 / 210,
          widthFraction: 30 / 210,
          topMm: 0,
          fillSlot: "secondary",
          opacity: 0.28,
          cornerRadiiMm: [0, 0, 0, 11],
        },
      ],
      noneMotifs: [
        {
          shape: "rect",
          xFraction: 0,
          widthFraction: 190 / 210,
          topMm: 0,
          heightMm: 11,
          fillSlot: "primary",
          cornerRadiiMm: [0, 0, 9, 0],
        },
        {
          shape: "rect",
          xFraction: 18 / 210,
          widthFraction: 144 / 210,
          topMm: 11,
          heightMm: 5,
          fillSlot: "secondary",
          cornerRadiiMm: [0, 0, 5, 5],
        },
        {
          shape: "rect",
          xFraction: 0,
          widthFraction: 1,
          topMm: 294,
          heightMm: 3,
          fillSlot: "accent",
        },
      ],
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: true, sidebarFraction: 0.3 },
  artwork: [],
};
export const SUNRISE: TemplateDefinition = {
  id: "sunrise",
  archetype: "editorial",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "3A2A24", accent: "F4C76A", paper: "FFF8F2" },
  margins: { top: 32, right: 23, bottom: 23, left: 25 },
  cover: {
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 60,
    photoAlign: "right",
    heroLeadMm: 24,
    photoAbsentLeadMm: 86,
    fieldAlignments: {
      eyebrow: "left",
      ortDatum: "right",
      name: "center",
      beruf: "center",
      lehrbeginn: "center",
    },
    decorationPlacement: "first-header",
    rows: [
      { fields: ["eyebrow", "ortDatum"], widths: [0.5, 0.5] },
      {
        fields: [
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger", "beilagenTitel", "beilagen"],
        ],
        widths: [1, 1],
        beforeMm: 12,
      },
    ],
    motifs: [
      {
        shape: "path",
        path: "M 0 0 L 100 0 L 100 67 C 100 100 28 100 0 74 L 0 0",
        xFraction: -12 / 210,
        widthFraction: 234 / 210,
        topMm: -14,
        heightMm: 101,
        fillSlot: "primary",
        endSlot: "secondary",
        angleDeg: 115,
      },
      {
        shape: "circle",
        xFraction: 92 / 210,
        widthFraction: 145 / 210,
        topMm: -32,
        heightMm: 112,
        fillSlot: "secondary",
        opacity: 0.4,
        radialFade: { innerPct: 0, outerPct: 100 },
      },
      {
        shape: "path",
        path: "M 0 25 C 22 0 76 0 100 28 L 100 100 L 0 100 L 0 25",
        xFraction: -17 / 210,
        widthFraction: 244 / 210,
        topMm: 236,
        heightMm: 82,
        fillSlot: "accent",
        endSlot: "secondary",
        angleDeg: 108,
        opacity: 0.92,
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
      motifs: [
        {
          shape: "rect",
          xFraction: 0,
          widthFraction: 1,
          topMm: 0,
          fillSlot: "primary",
          endSlot: "secondary",
          angleDeg: 90,
        },
      ],
      noneMotifs: [
        {
          shape: "rect",
          xFraction: 0,
          widthFraction: 1,
          topMm: 0,
          heightMm: 10,
          fillSlot: "primary",
          endSlot: "secondary",
          angleDeg: 90,
        },
        {
          shape: "circle",
          xFraction: 188 / 210,
          widthFraction: 12 / 210,
          topMm: 3,
          heightMm: 12,
          fillSlot: "accent",
          opacity: 0.28,
        },
        {
          shape: "rect",
          xFraction: 25 / 210,
          widthFraction: 22 / 210,
          topMm: 16.2,
          heightMm: 1.1,
          fillSlot: "accent",
          cornerRadiiMm: [0.55, 0.55, 0.55, 0.55],
        },
      ],
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: true, sidebarFraction: 0.3 },
  artwork: [],
};
/** Native cover rail columns and quiet paper chrome, configured without sidebar reconstruction. */
export const FOREST_FLOW: TemplateDefinition = {
  id: "forestFlow",
  archetype: "organic",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "1D2B27", accent: "9ABF9C", paper: "F5F8F4" },
  margins: { top: 32, right: 23, bottom: 23, left: 34 },
  cover: {
    fontSource: "dossier",
    margins: { top: 18, right: 14, bottom: 20, left: 7 },
    order: [
      "eyebrow",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
      "ortDatum",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 46,
    photoAlign: "right",
    fieldAlignments: {
      eyebrow: "center",
      ortDatum: "center",
      kontaktTitel: "center",
      kontakt: "center",
      name: "left",
      beruf: "left",
      lehrbeginn: "left",
      anTitel: "right",
      empfaenger: "right",
      beilagenTitel: "right",
      beilagen: "right",
    },
    fieldColorSlots: { eyebrow: "bg", ortDatum: "bg", kontaktTitel: "bg", kontakt: "bg" },
    fieldSpaceBeforeMm: {
      name: 40,
      kontaktTitel: 120,
      ortDatum: 12,
      anTitel: 18,
      beilagenTitel: 8,
    },
    decorationPlacement: "first-header",
    rows: [
      {
        fields: [
          ["eyebrow", "kontaktTitel", "kontakt", "ortDatum"],
          [],
          [
            "foto",
            "name",
            "beruf",
            "lehrbeginn",
            "anTitel",
            "empfaenger",
            "beilagenTitel",
            "beilagen",
          ],
        ],
        widths: [0.2, 0.15, 0.65],
      },
    ],
    motifs: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 52 / 210,
        topMm: 0,
        heightMm: 297,
        fillSlot: "primary",
      },
      {
        shape: "rect",
        xFraction: 52.6 / 210,
        widthFraction: 157.4 / 210,
        topMm: 0,
        heightMm: 82,
        fillSlot: "secondary",
        opacity: 0.3,
        cornerRadiiMm: [0, 0, 0, 38],
      },
      {
        shape: "rect",
        xFraction: 52 / 210,
        widthFraction: 0.8 / 210,
        topMm: 0,
        heightMm: 82,
        fillSlot: "accent",
        opacity: 0.9,
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      surface: "motifs",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: false, sidebarFraction: 0.3 },
  pageMotifs: {
    letter: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 10 / 210,
        topMm: 0,
        heightMm: 297,
        fillSlot: "primary",
      },
      {
        shape: "circle",
        xFraction: 5 / 210,
        widthFraction: 24 / 210,
        topMm: 14,
        heightMm: 24,
        fillSlot: "secondary",
        opacity: 0.2,
      },
      {
        shape: "rect",
        xFraction: 15 / 210,
        widthFraction: 15 / 210,
        topMm: 32,
        heightMm: 1.2,
        fillSlot: "accent",
        cornerRadiiMm: [0, 0.6, 0.6, 0],
      },
    ],
    cv: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 10 / 210,
        topMm: 0,
        heightMm: 297,
        fillSlot: "primary",
      },
      {
        shape: "circle",
        xFraction: 5 / 210,
        widthFraction: 24 / 210,
        topMm: 14,
        heightMm: 24,
        fillSlot: "secondary",
        opacity: 0.2,
      },
      {
        shape: "rect",
        xFraction: 15 / 210,
        widthFraction: 15 / 210,
        topMm: 32,
        heightMm: 1.2,
        fillSlot: "accent",
        cornerRadiiMm: [0, 0.6, 0.6, 0],
      },
    ],
  },
  artwork: [],
};
const VIOLET_PAGE_MOTIFS: readonly TemplateMotif[] = [
  {
    shape: "rect",
    xFraction: 155 / 210,
    widthFraction: 55 / 210,
    topMm: 0,
    heightMm: 17.5,
    fillSlot: "primary",
    endSlot: "secondary",
    angleDeg: 135,
    opacity: 0.18,
    cornerRadiiMm: [0, 0, 0, 5],
  },
  {
    shape: "rect",
    xFraction: 25 / 210,
    widthFraction: 28 / 210,
    topMm: 3,
    heightMm: 1.2,
    fillSlot: "accent",
    cornerRadiiMm: [0.6, 0.6, 0.6, 0.6],
  },
];
/** The same bounded cubic contour and radial primitives configure an independent violet field. */
export const VIOLET_PULSE: TemplateDefinition = {
  id: "violetPulse",
  archetype: "editorial",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "1F1733", accent: "D946EF", paper: "FAF7FF" },
  margins: { top: 32, right: 24, bottom: 23, left: 25 },
  cover: {
    fontSource: "dossier",
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 60,
    photoAlign: "right",
    heroLeadMm: 24,
    photoAbsentLeadMm: 86,
    fieldAlignments: {
      eyebrow: "left",
      ortDatum: "right",
      name: "center",
      beruf: "center",
      lehrbeginn: "center",
    },
    decorationPlacement: "first-header",
    rows: [
      { fields: ["eyebrow", "ortDatum"], widths: [0.5, 0.5] },
      {
        fields: [
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger", "beilagenTitel", "beilagen"],
        ],
        widths: [1, 1],
        beforeMm: 12,
      },
    ],
    motifs: [
      {
        shape: "path",
        path: "M 0 0 L 100 0 L 100 38 C 96 81 46 100 0 79 L 0 0",
        xFraction: -20 / 210,
        widthFraction: 250 / 210,
        topMm: -8,
        heightMm: 118,
        fillSlot: "primary",
        endSlot: "secondary",
        angleDeg: 135,
      },
      {
        shape: "circle",
        xFraction: 104 / 210,
        widthFraction: 138 / 210,
        topMm: -32,
        heightMm: 138,
        fillSlot: "secondary",
        opacity: 0.45,
        radialFade: { innerPct: 0, outerPct: 100 },
      },
      {
        shape: "circle",
        xFraction: 30 / 210,
        widthFraction: 92 / 210,
        topMm: 72,
        heightMm: 92,
        fillSlot: "accent",
        opacity: 0.16,
        radialFade: { innerPct: 0, outerPct: 100 },
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      surface: "motifs",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: true, sidebarFraction: 0.3 },
  pageMotifs: {
    letter: VIOLET_PAGE_MOTIFS,
    cv: VIOLET_PAGE_MOTIFS,
  },
  artwork: [],
};
/** Asymmetric editorial candidate: native split hero and shared two-tone stationery. */
export const STUDIO_3: TemplateDefinition = {
  id: "studio3",
  archetype: "editorial",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "18302D", accent: "E2A94B", paper: "F7FBFA" },
  margins: { top: 32, right: 23, bottom: 23, left: 25 },
  cover: {
    fontSource: "dossier",
    order: [
      "eyebrow",
      "ortDatum",
      "foto",
      "name",
      "beruf",
      "lehrbeginn",
      "kontaktTitel",
      "kontakt",
      "anTitel",
      "empfaenger",
      "beilagenTitel",
      "beilagen",
    ],
    align: "left",
    heroSpaceMm: 0,
    photoWidthMm: 48,
    photoAlign: "right",
    heroLeadMm: 18,
    photoAbsentLeadMm: 92,
    fieldAlignments: { name: "left", beruf: "left", lehrbeginn: "left", ortDatum: "right" },
    fieldColorSlots: { eyebrow: "bg", ortDatum: "bg" },
    decorationPlacement: "first-header",
    rows: [
      { fields: ["eyebrow", "ortDatum"], widths: [1, 1] },
      {
        fields: [
          ["kontaktTitel", "kontakt"],
          ["anTitel", "empfaenger", "beilagenTitel", "beilagen"],
        ],
        widths: [1, 1],
        beforeMm: 28,
      },
    ],
    motifs: [
      {
        shape: "path",
        path: "M 0 0 L 100 0 L 100 74 L 64 100 L 0 84",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 124,
        fillSlot: "primary",
      },
      {
        shape: "rect",
        xFraction: 126 / 210,
        widthFraction: 84 / 210,
        topMm: 0,
        heightMm: 90,
        cornerRadiiMm: [0, 0, 0, 36],
        fillSlot: "secondary",
        opacity: 0.94,
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 12,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 22,
      compactContinuationMm: 22,
      motifs: [
        {
          shape: "rect",
          xFraction: 146 / 210,
          widthFraction: 64 / 210,
          topMm: 0,
          fillSlot: "secondary",
        },
      ],
      noneMotifs: [
        {
          shape: "rect",
          xFraction: 0,
          widthFraction: 1,
          topMm: 0,
          heightMm: 22,
          fillSlot: "primary",
        },
        {
          shape: "rect",
          xFraction: 146 / 210,
          widthFraction: 64 / 210,
          topMm: 0,
          heightMm: 22,
          fillSlot: "secondary",
        },
      ],
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: true, sidebarFraction: 0.3 },
  artwork: [],
};
const WARM_2_PAGE_MOTIFS: readonly TemplateMotif[] = [
  {
    shape: "rect",
    xFraction: 0,
    widthFraction: 1,
    topMm: 0,
    heightMm: 16,
    cornerRadiiMm: [0, 0, 13, 0],
    fillSlot: "primary",
  },
  {
    shape: "circle",
    xFraction: 189 / 210,
    widthFraction: 28 / 210,
    topMm: 3,
    heightMm: 28,
    fillSlot: "secondary",
    opacity: 0.82,
  },
];
/** Organic candidate: shared centered native hero and quiet curved stationery. */
export const WARM_2: TemplateDefinition = {
  id: "warm2",
  archetype: "organic",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "16312D", accent: "D96C50", paper: "FFFAF2" },
  margins: { top: 32, right: 24, bottom: 23, left: 25 },
  cover: {
    ...HORIZON.cover,
    fontSource: "dossier",
    photoAlign: "center",
    heroLeadMm: 40,
    photoAbsentLeadMm: 105,
    fieldColorSlots: { eyebrow: "bg", ortDatum: "bg" },
    motifs: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 94,
        cornerRadiiMm: [0, 0, 72, 0],
        fillSlot: "primary",
      },
      {
        shape: "path",
        path: "M 0 0 L 100 0 L 100 30 C 100 70 83 92 67 100 L 50 100 C 25 100 0 77 0 49 L 0 0",
        xFraction: 134 / 210,
        widthFraction: 76 / 210,
        topMm: 0,
        heightMm: 74,
        fillSlot: "secondary",
        opacity: 0.92,
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 22,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      surface: "motifs",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: true, sidebarFraction: 0.3 },
  pageMotifs: { letter: WARM_2_PAGE_MOTIFS, cv: WARM_2_PAGE_MOTIFS },
  artwork: [],
};
/** Mature organic candidate: independently rounded counter-field and two-tone stationery. */
export const WARM_3: TemplateDefinition = {
  id: "warm3",
  archetype: "organic",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "24312E", accent: "C86648", paper: "FBF7EF" },
  margins: { top: 32, right: 24, bottom: 23, left: 27 },
  cover: {
    ...HORIZON.cover,
    fontSource: "dossier",
    photoWidthMm: 48,
    photoAlign: "right",
    heroLeadMm: 35,
    photoAbsentLeadMm: 103,
    fieldColorSlots: { eyebrow: "bg", ortDatum: "bg" },
    motifs: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 72,
        cornerRadiiMm: [0, 0, 34, 0],
        fillSlot: "primary",
      },
      {
        shape: "rect",
        xFraction: 126 / 210,
        widthFraction: 84 / 210,
        topMm: 0,
        heightMm: 72,
        cornerRadiiMm: [0, 0, 34, 34],
        fillSlot: "secondary",
        opacity: 0.94,
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 18,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      surface: "motifs",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
    },
  },
  cv: { sectionSpaceMm: 3.6, headingRule: true, sidebarFraction: 0.3 },
  pageMotifs: {
    letter: [
      { shape: "rect", xFraction: 0, widthFraction: 1, topMm: 0, heightMm: 7, fillSlot: "primary" },
      {
        shape: "rect",
        xFraction: 144 / 210,
        widthFraction: 66 / 210,
        topMm: 0,
        heightMm: 7,
        fillSlot: "secondary",
      },
    ],
    cv: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 10,
        fillSlot: "primary",
      },
      {
        shape: "rect",
        xFraction: 144 / 210,
        widthFraction: 66 / 210,
        topMm: 0,
        heightMm: 10,
        fillSlot: "secondary",
        opacity: 0.94,
      },
    ],
  },
  artwork: [],
};
/** White cover ink and readable interior palettes are independent declarative choices. */
export const VERLAUF_2: TemplateDefinition = {
  id: "verlauf2",
  archetype: "graphic",
  typography: { font: "Arial", bodyPt: 10.5, namePt: 24, headingPt: 12, heroPt: 26 },
  colors: { ink: "FFFFFF", accent: "9BE7E5", paper: "F5F9FF" },
  interiorPaletteSource: "dossier",
  margins: { top: 24, right: 24, bottom: 22, left: 26 },
  cover: {
    ...HORIZON.cover,
    fontSource: "dossier",
    fieldPaletteMode: "uniform",
    margins: { top: 20, right: 22, bottom: 20, left: 22 },
    fieldColorSlots: Object.fromEntries(
      [
        "eyebrow",
        "ortDatum",
        "kicker",
        "name",
        "beruf",
        "lehrbeginn",
        "kontaktTitel",
        "kontakt",
        "anTitel",
        "empfaenger",
        "beilagenTitel",
        "beilagen",
      ].map((id) => [id, "ink"]),
    ),
    motifs: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 297,
        fillSlot: "primary",
        angleDeg: 148,
        gradientStops: [
          { slot: "primary", offsetPct: 2 },
          { slot: "secondary", offsetPct: 68 },
          { slot: "accent", offsetPct: 118 },
        ],
      },
      {
        shape: "circle",
        xFraction: 116 / 210,
        widthFraction: 126 / 210,
        topMm: -22,
        heightMm: 126,
        fillColor: "FFFFFF",
        opacity: 0.22,
        radialFade: { innerPct: 0, outerPct: 100 },
      },
      {
        shape: "circle",
        xFraction: -42 / 210,
        widthFraction: 142 / 210,
        topMm: 192,
        heightMm: 142,
        fillColor: "FFFFFF",
        opacity: 0.14,
        radialFade: { innerPct: 0, outerPct: 100 },
      },
    ],
  },
  letter: {
    paragraphSpaceMm: 3,
    lineHeight: 1.2,
    recipientGapMm: 12,
    fontSource: "dossier",
    keepTailTogether: true,
  },
  chrome: {
    headerDistanceMm: 18,
    footerDistanceMm: 12,
    ignoreEmptyHeader: true,
    lineMetricFactor: 1.4,
    defaultContact: { heightMm: 36, gapMm: 4 },
    band: {
      surfaceSource: "descriptor",
      surface: "motifs",
      fillSlot: "primary",
      accentSlot: "secondary",
      compactFirstMm: 14,
      compactContinuationMm: 14,
    },
  },
  cv: { sectionSpaceMm: 4, headingRule: true, sidebarFraction: 0.3 },
  pageMotifs: {
    letter: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 9,
        fillSlot: "primary",
        endSlot: "secondary",
        angleDeg: 90,
      },
      {
        shape: "rect",
        xFraction: 178 / 210,
        widthFraction: 32 / 210,
        topMm: 0,
        heightMm: 16,
        cornerRadiiMm: [8, 8, 8, 8],
        fillSlot: "accent",
        opacity: 0.28,
      },
    ],
    cv: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 9,
        fillSlot: "primary",
        endSlot: "secondary",
        angleDeg: 90,
      },
      {
        shape: "rect",
        xFraction: 178 / 210,
        widthFraction: 32 / 210,
        topMm: 0,
        heightMm: 16,
        cornerRadiiMm: [8, 8, 8, 8],
        fillSlot: "accent",
        opacity: 0.28,
      },
    ],
  },
  artwork: [],
};
/** A second, independently configured consumer of the shared palette/gradient primitives. */
export const VERLAUF_3: TemplateDefinition = {
  ...VERLAUF_2,
  id: "verlauf3",
  colors: { ink: "FFFFFF", accent: "F4BB8A", paper: "FFF8F5" },
  margins: { top: 24, right: 24, bottom: 22, left: 27 },
  cover: {
    ...VERLAUF_2.cover,
    motifs: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 297,
        fillSlot: "primary",
        angleDeg: 162,
        gradientStops: [
          { slot: "primary", offsetPct: 0 },
          { slot: "secondary", offsetPct: 72 },
          { slot: "accent", offsetPct: 125 },
        ],
      },
      {
        shape: "circle",
        xFraction: -28 / 210,
        widthFraction: 118 / 210,
        topMm: -30,
        heightMm: 118,
        fillColor: "FFFFFF",
        opacity: 0.13,
        radialFade: { innerPct: 0, outerPct: 100 },
      },
      {
        shape: "circle",
        xFraction: 126 / 210,
        widthFraction: 128 / 210,
        topMm: 184,
        heightMm: 128,
        fillColor: "FFFFFF",
        opacity: 0.16,
        radialFade: { innerPct: 0, outerPct: 100 },
      },
    ],
  },
  pageMotifs: {
    letter: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 9,
        fillSlot: "primary",
        endSlot: "secondary",
        angleDeg: 90,
      },
      {
        shape: "rect",
        xFraction: 176 / 210,
        widthFraction: 34 / 210,
        topMm: 0,
        heightMm: 16,
        cornerRadiiMm: [8, 8, 8, 8],
        fillSlot: "accent",
        opacity: 0.28,
      },
    ],
    cv: [
      {
        shape: "rect",
        xFraction: 0,
        widthFraction: 1,
        topMm: 0,
        heightMm: 9,
        fillSlot: "primary",
        endSlot: "secondary",
        angleDeg: 90,
      },
      {
        shape: "rect",
        xFraction: 176 / 210,
        widthFraction: 34 / 210,
        topMm: 0,
        heightMm: 16,
        cornerRadiiMm: [8, 8, 8, 8],
        fillSlot: "accent",
        opacity: 0.28,
      },
    ],
  },
};
export const NEXT_TEMPLATES: Readonly<Record<string, TemplateDefinition>> = {
  brief: BRIEF,
  freundlich: WARM,
  prism: PRISM,
  human: HUMAN,
  orbit: ORBIT,
  cove: COVE,
  glow: GLOW,
  horizon: HORIZON,
  monoLuxe: MONO_LUXE,
  ledger: LEDGER,
  ribbon: RIBBON,
  sunrise: SUNRISE,
  forestFlow: FOREST_FLOW,
  violetPulse: VIOLET_PULSE,
  studio3: STUDIO_3,
  warm2: WARM_2,
  warm3: WARM_3,
  verlauf2: VERLAUF_2,
  verlauf3: VERLAUF_3,
};
export function nextTemplate(id: string): TemplateDefinition {
  const template = NEXT_TEMPLATES[id];
  if (!template) throw new Error(`DOCX Next template ${id} has not passed migration gates.`);
  return template;
}
